-- =============================================================================
-- STEP 0 of 2 (run first) — appointments.appointment_id needs a generated value
-- =============================================================================
-- Run this BEFORE 01_booking_enum.sql / 02_booking_schema.sql.
-- It fixes a pre-existing bug: booking creation is currently impossible.
--
-- THE BUG
--   appointments.appointment_id is  INTEGER UNIQUE NOT NULL  (DEFAULT NULL)
--   A DEFAULT of NULL does not satisfy NOT NULL. Any INSERT that omits the
--   column supplies an explicit NULL, which fails the NOT NULL check.
--   components/appointments/BookingModal.tsx:145 omits it, so every booking
--   request fails. Nothing in the repository ever writes this column.
--
-- WHAT IT IS INTENDED TO BE  (all verified, not assumed)
--   * NOT the primary key. `id BIGINT GENERATED ALWAYS AS IDENTITY` is, and
--     every mutation keys on it: lib/admin/service.ts:389 and :395 both use
--     .eq('id', bookingId), and app/admin/bookings/page.tsx:123,147 pass
--     booking.id.
--   * A human-facing reference number. MIGRATION_PLAN.md:128 documents it as
--     "5 digit ID", and app/admin/bookings/page.tsx:172 renders it as
--     #{String(b.appointment_id).padStart(5, '0')}.
--   * Nothing references it. Grep over supabase/ finds no FOREIGN KEY to it,
--     and probes confirm no live table carries a matching column: feedbacks
--     .appointment_id, agreements.booking_id and agreements.appointment_id are
--     all absent. The only REFERENCES to appointments anywhere are the three
--     added by 02_booking_schema.sql, and all three point at appointments(id),
--     NOT at appointment_id.
--   * The sibling convention is profiles.custom_id — a short human-facing
--     number generated at registration. This column is the same idea per
--     booking, which is why it should be generated rather than typed.
--
-- WHY A SEQUENCE DEFAULT, NOT AN IDENTITY COLUMN
--   ALTER COLUMN ... ADD GENERATED BY DEFAULT AS IDENTITY would also work, but a
--   plain sequence DEFAULT keeps the door open for a caller to supply an
--   explicit reference (e.g. migrating in a legacy ID). A plain DEFAULT never
--   rejects an explicit value, so it is strictly less likely to break code
--   that has not been read yet. Nothing can silently lose data either way: the
--   UNIQUE constraint on the column is already in place and still enforces
--   uniqueness after the fact.
--
-- WHY IT IS SAFE
--   * Adds no column, changes no type, drops nothing, deletes nothing.
--   * Existing rows keep their current values — the default only applies to
--     rows inserted after this runs. (The table is currently empty: the API
--     returns [] and Content-Range */*.)
--   * OWNED BY ties the sequence's lifetime to the column, so dropping the
--     column later drops the sequence too. No orphan.
--   * Idempotent, and the seeding step can never rewind the counter: it only
--     advances a sequence that has never been used.
-- =============================================================================

-- Owned by the column: no orphan sequence if the column is ever dropped.
CREATE SEQUENCE IF NOT EXISTS public.appointments_reference_seq
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    OWNED BY public.appointments.appointment_id;

-- Advance past any rows that already exist — exactly once.
--
-- Guarded on is_called so that RE-RUNNING THIS FILE CANNOT REWIND THE
-- COUNTER. Without that guard, a second run would reset the sequence to
-- MAX+1 (or 1 on an empty table) and start handing out values that may already
-- be taken, producing duplicate-reference failures the moment bookings exist.
DO $$
DECLARE
    v_is_called BOOLEAN;
    v_max        INTEGER;
BEGIN
    SELECT is_called INTO v_is_called FROM public.appointments_reference_seq;

    IF NOT COALESCE(v_is_called, false) THEN
        SELECT COALESCE(MAX(appointment_id), 0) INTO v_max FROM public.appointments;

        IF v_max > 0 THEN
            EXECUTE format(
                'SELECT setval(%L, %s, false)',
                'public.appointments_reference_seq', v_max + 1);
            RAISE NOTICE 'appointment_id sequence seeded to %', v_max + 1;
        ELSE
            RAISE NOTICE 'appointments is empty; sequence starts at 1';
        END IF;
    ELSE
        RAISE NOTICE 'appointment_id sequence already in use; left untouched';
    END IF;
END $$;

-- The actual fix.
ALTER TABLE public.appointments
    ALTER COLUMN appointment_id SET DEFAULT nextval('public.appointments_reference_seq');

COMMENT ON COLUMN public.appointments.appointment_id IS
    'Human-facing 5-digit booking reference (e.g. 00001). Displayed in the admin booking list. NOT the primary key — appointments.id is. Generated by appointments_reference_seq; may still be supplied explicitly for legacy imports.';

-- -----------------------------------------------------------------------------
-- Self-check.
-- Expect appointment_id_nullable = NO (unchanged) and a sequence default present.
-- -----------------------------------------------------------------------------
SELECT
    is_nullable,
    column_default
  FROM information_schema.columns
 WHERE table_schema = 'public'
   AND table_name   = 'appointments'
   AND column_name  = 'appointment_id';
-- PASS: is_nullable = 'NO', column_default contains 'appointments_reference_seq'


-- =============================================================================
-- STILL BLOCKED — NOT fixed by this file
-- =============================================================================
-- appointments.email is  VARCHAR(255) NOT NULL  and BookingModal.tsx:145 also
-- omits it. Booking creation will still fail with a not-null violation until
-- the insert sends it.
--
-- Recommended fix (frontend, one line, no schema change):
--     .insert({ ...,  email: user.email, ... })
-- The authenticated user's email is authoritative, it already exists in
-- auth.users, and the column is a plain VARCHAR so nothing about the schema
-- needs to move. This is deliberately NOT solved with a database trigger or a
-- default: the value is knowable in the browser, and inventing it in the
-- database would mean storing a copy of a fact the database cannot verify.
--
-- Verified alongside this bug: notifications.cta_url DOES exist, so the
-- notification insert in BookingModal.tsx:163 is fine as written.
-- =============================================================================